### ISSUE TITLE
cellrenderer with reactCellRendererFactory not working 

### ISSUE THREAD

**Issue by dileep8014** [ceolter/ag-grid-react#2] opened 2016-02-12 21:43 UTC
while using reactCellRendererFactory as a cell rederer getting below warning and exception

 Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).
Uncaught invariant.js?568c:39 Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

**Comment by ceolter** [comment] 2016-02-13 14:51
the example is working: https://github.com/ceolter/ag-grid-react-example
so the library does work. as to why it's not working for you i cannot say.
sounds like you are not importing the ag-grid-react library correctly?

as i can't reproduce this, and sounds like user error, am closing the issue.

**Closed by ceolter** 2016-02-13 14:51 UTC
