### ISSUE TITLE
Autosizing the columns are not working with sizeColumnsToFit

### ISSUE THREAD

**Issue by dileep8014** [ceolter/ag-grid-react#4] opened 2016-02-17 02:27 UTC
I tried auto sizing the columns on render and called this method as this.api.sizeColumnsToFit() but nothing happened as expected its not auto sizing the columns as expected . 

Before i was using regular ag-grid grid inside my react application and it was working fine .
i tried calling this in onGridReady method like below 

onGridReady(params) {
	    this.api = params.api;
	    this.columnApi = params.columnApi;
           this.api.sizeColumnsToFit();
  }

<AgGridReact
	        onGridReady={this.onGridReady.bind(this)}
	   		columnDefs={columnDefs}
	   		rowData={json}
	   		onRowDeselected={ this.rowDeselectedFunc.bind(this)}
	   		onSelectionChanged={this.onSelectionChanged.bind(this)}
	   		rowSelection="multiple"
   			suppressRowClickSelection="true"
	   		suppressLoadingOverlay="true"
	   		enableSorting="true"
	   		enableFilter="true"
	   		enableColResize="true"
	   		rowHeight="25"
		/>

**Comment by ceolter** [comment] 2016-02-17 07:33
this example shows them both working side by side.
https://www.ag-grid.com/angular-grid-resizing/index.php

the internals of the grid doesn't use react or any other framework, so just because you are in react should not change things. this sounds like use error. i can't see anything wrong with the above. if you create a plunker with it reproduced i can take a look. as this is a question, i'm closing, github issues should be or when something is wrong with the grid.

**Closed by ceolter** 2016-02-17 07:33 UTC

**Comment by dvirHam** [comment] 2016-03-28 09:49
I think it's because of the "onGridReady" function, I have promblem with her too.

**Comment by antgonzales** [comment] 2018-05-09 19:00
I'm currently having this issue with a React app using Ag-grid. I've attempted to set a timeout and attempted to listen for `DOMContentLoaded` with no success.

```
  onGridReady(params) {
    params.api.sizeColumnsToFit();
  }
...
render () {
  <AgGridReact
    onGridReady={this.onGridReady.bind(this)}
    .../>
}
```
![image](https://user-images.githubusercontent.com/3740655/39833918-74932880-5399-11e8-9902-ec580d3e054d.png)
