### ISSUE TITLE
HTMLElement is not defined

### ISSUE THREAD

**Issue by fastfedora** [ceolter/ag-grid-react#24] opened 2016-06-28 19:36 UTC
Getting an `HTMLElement is not defined` trying to use ag-Grid within a React application compiled using webpack. Error stack is below.

```
node_modules\ag-grid\dist\lib\gridCore.js:285
})();
  ^
ReferenceError: HTMLElement is not defined
    at node_modules\ag-grid\dist\lib\gridCore.js:237:35
    at Object.<anonymous> (node_modules\ag-grid\dist\lib\gridCore.js:285:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (ag-grid\dist\lib\misc\focusService.js:18:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (node_modules\ag-grid\dist\lib\rendering\renderedCell.js:37:22)
```

Using code:

```
import {AgGridReact} from 'ag-grid-react';

<AgGridReact columnDefs={columnDefs} rowData={rowData} />
```

[Other people](https://www.google.com/#q=%22HTMLElement+is+not+defined%22+ag-grid) are apparently also having this problem. Sounds like it may be due ag-Grid not supporting server-side rendering.

**Comment by stevez86** [comment] 2016-07-12 21:01
+1 Getting the same error, using [react-redux-universal-hot-example](https://github.com/erikras/react-redux-universal-hot-example).

**Comment by ceolter** [comment] 2016-07-13 07:47
you are probably using server side rendering?

ag-Grid doesn't support server side rendering. to do it, you would need to provide a mocked dom somehow.

i'm assuming this is the issue, as we have seen "HTMLElement is not defined" before and always was due to this, so closing. if not this issue, then please advise how we can reproduce and reopen! (with a plunker would be great, as we are not in the habit of throwing up projects in different configurations)

**Closed by ceolter** 2016-07-13 07:47 UTC

**Comment by fastfedora** [comment] 2016-07-13 11:27
One thing that may help is noting in the documentation that ad-Grid React is a thin wrapper around the ad-Grid component and not a pure React component. So anything relying on React features like server-side rendering won't work.

There's several articles out there promoting ad-Grid as an alternative to other React grids like Fixed Data Table and Griddle, which is where some of the confusion lies. When I originally tried ad-Grid React, I thought it was a ported version of ad-Grid that was fully written in React. While it's a beautiful grid, we're using only pure React components in our application, so we can do things like server-side rendering. We wound up going with Griddle instead.

**Comment by stevez86** [comment] 2016-07-13 19:19
I thought I had SSR disabled but the boilerplate I'm using appears to have an issue with disabling server side rendering.

@ceolter ag-grid 3.3.3 and ag-grid-react 3.3.1 don't throw this same error. I'm curious why and will be using that until we can figure the boilerplate issue.

@fastfedora Appreciate the recs, will look into those if SSR becomes a requirement.

**Comment by stevez86** [comment] 2016-07-13 21:35
Adding this line to the top of gridCore.js and agCheckbox.js hacked me out of the error:

'var HTMLElement = typeof HTMLElement === 'undefined' ? function(){} : HTMLElement;'

Still looking into a permanent solution through the boilerplate

**Comment by zatziky** [comment] 2016-08-26 07:45
We need to run tests using mocha and webpack. @ceolter, the work around from @stevez86 is a good solution. Would you implement it in the next release? It's not comfortable to rewrite compiled libs in order to add those lines.

**Comment by ceolter** [comment] 2016-08-31 10:18
@stevez86 @zatziky I've had a look at gridCore.ts, it's using HTMLElement as a type - I thought all types were stripped out when compiling TypeScript to JavaScript, so why is it looking for a type at runtime?

**Comment by zatziky** [comment] 2016-08-31 11:27
@ceolter If I only knew. I jumped directly to `redux` without any previous knowledge of `reactjs` and currently our project is client side.

**Comment by zatziky** [comment] 2016-09-01 08:58
I am posting where the error appears in `gridCore.js` but I don't have any clues still:

```
var GridCore = (function () {
    function GridCore(loggerFactory) {
        this.destroyFunctions = [];
        this.logger = loggerFactory.create('GridCore');
    }
    GridCore.prototype.init = function () {
        var _this = this;
        // and the last bean, done in it's own section, as it's optional
        var toolPanelGui;
        var eSouthPanel = this.createSouthPanel();
        if (this.toolPanel && !this.gridOptionsWrapper.isForPrint()) {
            toolPanelGui = this.toolPanel.getGui();
        }
        var createTopPanelGui = this.createNorthPanel();
        this.eRootPanel = new borderLayout_1.BorderLayout({
            center: this.gridPanel.getLayout(),
            east: toolPanelGui,
            north: createTopPanelGui,
            south: eSouthPanel,
            dontFill: this.gridOptionsWrapper.isForPrint(),
            name: 'eRootPanel'
        });
        // see what the grid options are for default of toolbar
        this.showToolPanel(this.gridOptionsWrapper.isShowToolPanel());
        this.eGridDiv.appendChild(this.eRootPanel.getGui());
        // if using angular, watch for quickFilter changes
        if (this.$scope) {
            this.$scope.$watch(this.quickFilterOnScope, function (newFilter) { return _this.filterManager.setQuickFilter(newFilter); });
        }
        if (!this.gridOptionsWrapper.isForPrint()) {
            this.addWindowResizeListener();
        }
        this.doLayout();
        this.finished = false;
        this.periodicallyDoLayout();
        this.eventService.addEventListener(events_1.Events.EVENT_COLUMN_ROW_GROUP_CHANGED, this.onRowGroupChanged.bind(this));
        this.eventService.addEventListener(events_1.Events.EVENT_COLUMN_EVERYTHING_CHANGED, this.onRowGroupChanged.bind(this));
        this.onRowGroupChanged();
        this.logger.log('ready');
    };
    GridCore.prototype.createNorthPanel = function () {
        var _this = this;
        if (!this.gridOptionsWrapper.isEnterprise()) {
            return null;
        }
        var topPanelGui = document.createElement('div');
        var dropPanelVisibleListener = this.onDropPanelVisible.bind(this);
        this.rowGroupComp = this.rowGroupCompFactory.create();
        this.pivotComp = this.pivotCompFactory.create();
        topPanelGui.appendChild(this.rowGroupComp.getGui());
        topPanelGui.appendChild(this.pivotComp.getGui());
        this.rowGroupComp.addEventListener(component_1.Component.EVENT_VISIBLE_CHANGED, dropPanelVisibleListener);
        this.pivotComp.addEventListener(component_1.Component.EVENT_VISIBLE_CHANGED, dropPanelVisibleListener);
        this.destroyFunctions.push(function () {
            _this.rowGroupComp.removeEventListener(component_1.Component.EVENT_VISIBLE_CHANGED, dropPanelVisibleListener);
            _this.pivotComp.removeEventListener(component_1.Component.EVENT_VISIBLE_CHANGED, dropPanelVisibleListener);
        });
        this.onDropPanelVisible();
        return topPanelGui;
    };
    GridCore.prototype.onDropPanelVisible = function () {
        var bothVisible = this.rowGroupComp.isVisible() && this.pivotComp.isVisible();
        this.rowGroupComp.addOrRemoveCssClass('ag-width-half', bothVisible);
        this.pivotComp.addOrRemoveCssClass('ag-width-half', bothVisible);
    };
    GridCore.prototype.getRootGui = function () {
        return this.eRootPanel.getGui();
    };
    GridCore.prototype.createSouthPanel = function () {
        if (!this.statusBar && this.gridOptionsWrapper.isEnableStatusBar()) {
            console.warn('ag-Grid: status bar is only available in ag-Grid-Enterprise');
        }
        var statusBarEnabled = this.statusBar && this.gridOptionsWrapper.isEnableStatusBar();
        var paginationPanelEnabled = this.gridOptionsWrapper.isRowModelPagination() && !this.gridOptionsWrapper.isForPrint();
        if (!statusBarEnabled && !paginationPanelEnabled) {
            return null;
        }
        var eSouthPanel = document.createElement('div');
        if (statusBarEnabled) {
            eSouthPanel.appendChild(this.statusBar.getGui());
        }
        if (paginationPanelEnabled) {
            eSouthPanel.appendChild(this.paginationController.getGui());
        }
        return eSouthPanel;
    };
    GridCore.prototype.onRowGroupChanged = function () {
        if (!this.rowGroupComp) {
            return;
        }
        var rowGroupPanelShow = this.gridOptionsWrapper.getRowGroupPanelShow();
        if (rowGroupPanelShow === constants_1.Constants.ALWAYS) {
            this.rowGroupComp.setVisible(true);
        }
        else if (rowGroupPanelShow === constants_1.Constants.ONLY_WHEN_GROUPING) {
            var grouping = !this.columnController.isRowGroupEmpty();
            this.rowGroupComp.setVisible(grouping);
        }
        else {
            this.rowGroupComp.setVisible(false);
        }
        this.eRootPanel.doLayout();
    };
    GridCore.prototype.addWindowResizeListener = function () {
        var eventListener = this.doLayout.bind(this);
        window.addEventListener('resize', eventListener);
        this.destroyFunctions.push(function () { return window.removeEventListener('resize', eventListener); });
    };
    GridCore.prototype.periodicallyDoLayout = function () {
        var _this = this;
        if (!this.finished) {
            var intervalMillis = this.gridOptionsWrapper.getLayoutInterval();
            // if interval is negative, this stops the layout from happening
            if (intervalMillis > 0) {
                setTimeout(function () {
                    _this.doLayout();
                    _this.gridPanel.periodicallyCheck();
                    _this.periodicallyDoLayout();
                }, intervalMillis);
            }
            else {
                // if user provided negative number, we still do the check every 5 seconds,
                // in case the user turns the number positive again
                setTimeout(function () {
                    _this.periodicallyDoLayout();
                }, 5000);
            }
        }
    };
    GridCore.prototype.showToolPanel = function (show) {
        if (show && !this.toolPanel) {
            console.warn('ag-Grid: toolPanel is only available in ag-Grid Enterprise');
            this.toolPanelShowing = false;
            return;
        }
        this.toolPanelShowing = show;
        if (this.toolPanel) {
            this.toolPanel.setVisible(show);
            this.eRootPanel.doLayout();
        }
    };
    GridCore.prototype.isToolPanelShowing = function () {
        return this.toolPanelShowing;
    };
    GridCore.prototype.destroy = function () {
        this.finished = true;
        this.eGridDiv.removeChild(this.eRootPanel.getGui());
        this.logger.log('Grid DOM removed');
        this.destroyFunctions.forEach(function (func) { return func(); });
    };
    GridCore.prototype.ensureNodeVisible = function (comparator) {
        if (this.doingVirtualPaging) {
            throw 'Cannot use ensureNodeVisible when doing virtual paging, as we cannot check rows that are not in memory';
        }
        // look for the node index we want to display
        var rowCount = this.rowModel.getRowCount();
        var comparatorIsAFunction = typeof comparator === 'function';
        var indexToSelect = -1;
        // go through all the nodes, find the one we want to show
        for (var i = 0; i < rowCount; i++) {
            var node = this.rowModel.getRow(i);
            if (comparatorIsAFunction) {
                if (comparator(node)) {
                    indexToSelect = i;
                    break;
                }
            }
            else {
                // check object equality against node and data
                if (comparator === node || comparator === node.data) {
                    indexToSelect = i;
                    break;
                }
            }
        }
        if (indexToSelect >= 0) {
            this.gridPanel.ensureIndexVisible(indexToSelect);
        }
    };
    GridCore.prototype.doLayout = function () {
        // need to do layout first, as drawVirtualRows and setPinnedColHeight
        // need to know the result of the resizing of the panels.
        var sizeChanged = this.eRootPanel.doLayout();
        // both of the two below should be done in gridPanel, the gridPanel should register 'resize' to the panel
        if (sizeChanged) {
            this.rowRenderer.drawVirtualRows();
            var event = {
                clientWidth: this.eRootPanel.getGui().clientWidth,
                clientHeight: this.eRootPanel.getGui().clientHeight
            };
            this.eventService.dispatchEvent(events_1.Events.EVENT_GRID_SIZE_CHANGED, event);
        }
    };
    __decorate([
        context_1.Autowired('gridOptions'), 
        __metadata('design:type', Object)
    ], GridCore.prototype, "gridOptions", void 0);
    __decorate([
        context_1.Autowired('gridOptionsWrapper'), 
        __metadata('design:type', gridOptionsWrapper_1.GridOptionsWrapper)
    ], GridCore.prototype, "gridOptionsWrapper", void 0);
    __decorate([
        context_1.Autowired('paginationController'), 
        __metadata('design:type', paginationController_1.PaginationController)
    ], GridCore.prototype, "paginationController", void 0);
    __decorate([
        context_1.Autowired('rowModel'), 
        __metadata('design:type', Object)
    ], GridCore.prototype, "rowModel", void 0);
    __decorate([
        context_1.Autowired('columnController'), 
        __metadata('design:type', columnController_1.ColumnController)
    ], GridCore.prototype, "columnController", void 0);
    __decorate([
        context_1.Autowired('rowRenderer'), 
        __metadata('design:type', rowRenderer_1.RowRenderer)
    ], GridCore.prototype, "rowRenderer", void 0);
    __decorate([
        context_1.Autowired('filterManager'), 
        __metadata('design:type', filterManager_1.FilterManager)
    ], GridCore.prototype, "filterManager", void 0);
    __decorate([
        context_1.Autowired('eventService'), 
        __metadata('design:type', eventService_1.EventService)
    ], GridCore.prototype, "eventService", void 0);
    __decorate([
        context_1.Autowired('gridPanel'), 
        __metadata('design:type', gridPanel_1.GridPanel)
    ], GridCore.prototype, "gridPanel", void 0);
    __decorate([
        context_1.Autowired('eGridDiv'), 
        __metadata('design:type', HTMLElement)
    ], GridCore.prototype, "eGridDiv", void 0);
    __decorate([
        context_1.Autowired('$scope'), 
        __metadata('design:type', Object)
    ], GridCore.prototype, "$scope", void 0);
    __decorate([
        context_1.Autowired('quickFilterOnScope'), 
        __metadata('design:type', String)
    ], GridCore.prototype, "quickFilterOnScope", void 0);
    __decorate([
        context_1.Autowired('popupService'), 
        __metadata('design:type', popupService_1.PopupService)
    ], GridCore.prototype, "popupService", void 0);
    __decorate([
        context_1.Autowired('focusedCellController'), 
        __metadata('design:type', focusedCellController_1.FocusedCellController)
    ], GridCore.prototype, "focusedCellController", void 0);
    __decorate([
        context_1.Optional('rowGroupCompFactory'), 
        __metadata('design:type', Object)
    ], GridCore.prototype, "rowGroupCompFactory", void 0);
    __decorate([
        context_1.Optional('pivotCompFactory'), 
        __metadata('design:type', Object)
    ], GridCore.prototype, "pivotCompFactory", void 0);
    __decorate([
        context_1.Optional('toolPanel'), 
        __metadata('design:type', component_1.Component)
    ], GridCore.prototype, "toolPanel", void 0);
    __decorate([
        context_1.Optional('statusBar'), 
        __metadata('design:type', component_1.Component)
    ], GridCore.prototype, "statusBar", void 0);
    __decorate([
        context_1.PostConstruct, 
        __metadata('design:type', Function), 
        __metadata('design:paramtypes', []), 
        __metadata('design:returntype', void 0)
    ], GridCore.prototype, "init", null);
    __decorate([
        context_1.PreDestroy, 
        __metadata('design:type', Function), 
        __metadata('design:paramtypes', []), 
        __metadata('design:returntype', void 0)
    ], GridCore.prototype, "destroy", null);
    GridCore = __decorate([
        context_1.Bean('gridCore'),
        __param(0, context_1.Qualifier('loggerFactory')), 
        __metadata('design:paramtypes', [logger_1.LoggerFactory])
    ], GridCore);
    return GridCore;
})();
```

More accurately it's these lines:

```
__decorate([
        context_1.Autowired('eGridDiv'), 
        __metadata('design:type', HTMLElement)
    ], GridCore.prototype, "eGridDiv", void 0);
```

**Comment by ceolter** [comment] 2016-09-02 12:52
i don't have it reproduced, so i'm a bit blind with regards the solution.

i'm happy to put code in if i know what it's doing - however the solution above doesn't make sense to me. if someone can explain it to me so i know what i'm coding, that would help.

so question still stands, why does putting definition information in help the generated javascript???

**Comment by zatziky** [comment] 2016-09-05 07:37
I have finally found a solution! I use `webpack` with `mocha`  (and `mocha-webpack`) in my test environment. 

1. First install [jsdom-global](https://github.com/rstacruz/jsdom-global): `npm install jsdom-global --save-dev` 

2. In `mocha.opts` or `mocha-webpack.opts` add `--require jsdom-global/register`




@ceolter In order to reproduce you can run `mocha` tests on front-end and in a test file you can include `ag-grid- react`.  That should be sufficient.

**Comment by ceolter** [comment] 2016-09-08 10:49
@zatziky cool, thanks for the feedback

**Comment by saivikas7875** [comment] 2016-09-27 20:01
@ceolter, thanks for the effort on v6.0.1 

Were you able to reproduce the `HTMLElement is not defined` issue?

**Comment by ceolter** [comment] 2016-10-11 09:00
@saivikas7875 no - but i haven't tried to be honest.

**Comment by pete-otaqui** [comment] 2017-01-03 09:46
I am using `webpack` for packaging, `tape` for testing, `enzyme` for rendering react components, and the suggested `jsdom` shim - all so that I can run tests under `node`, rather than in a browser.

Running tests is then achieved by simply specifying `babel-node tests.js` in the correct `package.json` scripts entry, or however else you prefer.

Given that, I have a `tests.js` entry point that looks like this, you can see where I have _also_ added HTMLElement to the global namespace to fix these errors, on top of the already-suggested enzyme / jsdom shimming:

```js

import JSDOM from 'jsdom';
import glob from 'glob';

/*
 * Setup JSDOM to allow node.js based react dom rendering,
as suggested by `enzyme` here:
https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md
 */

const jsdom = JSDOM.jsdom;
var exposedProperties = ['window', 'navigator', 'document'];
global.document = jsdom('');
global.window = document.defaultView;
Object.keys(document.defaultView).forEach((property) => {
  if (typeof global[property] === 'undefined') {
    exposedProperties.push(property);
    global[property] = document.defaultView[property];
  }
});
global.navigator = {
  userAgent: 'node.js'
};

// NOTE - this line stops errors being thrown. I guess it might be even
// better to set it to be jsdom's own HTMLElement?
global.HTMLElement = () => {};

// now require all the test files, I prefer glob to webpack magic:
glob.sync(`${__dirname}/src/js/**/*.test.js`).forEach((file) => {
  require(file);
});
```

If anyone's interested, the actual tests then look like this:

```js
import tape from 'tape';
import React from 'react';
import { mount } from 'enzyme';

import SomeComponent from 'some-component';

tape('SomeComponent behaves itself', (t) => {
  t.plan(1);
  const wrapper = mount(<SomeComponent />);
  t.ok(wrapper.text().match(/I am some component/));
});
```

**Comment by dvoaviarison** [comment] 2017-02-13 11:22
Server side you could do this

```js
global.HTMLElement = typeof HTMLElement === 'undefined' ? () => {} : HTMLElement;
global.HTMLSelectElement = typeof HTMLSelectElement === 'undefined' ? () => {} : HTMLSelectElement;
```
